export const ELIGIBILITY_CONDITIONS = [
  ['adhd', 'ADHD (Attention Deficit Hyperactivity Disorder)'],
  ['agoraphobia', 'Agoraphobia'],
  ['anxiety', 'Anxiety'],
  ['arthritis', 'Arthritis'],
  ['autistic-spectrum-disorder', 'Autistic Spectrum Disorder'],
  ['breast-pain', 'Breast Pain'],
  ['cancer-related-appetite-loss', 'Cancer Related Appetite Loss'],
  ['cancer-related-pain-and-secondary-symptoms', 'Cancer Related Pain and Other Secondary Symptoms'],
  ['chemotherapy-induced-nausea-and-vomiting', 'Chemotherapy Induced Nausea and Vomiting'],
  ['chronic-fatigue-syndrome-me', 'Chronic Fatigue Syndrome (ME)'],
  ['chronic-pain', 'Chronic Pain'],
  ['cluster-headache', 'Cluster Headache'],
  ['complex-regional-pain-syndrome', 'Complex Regional Pain Syndrome'],
  ['crohns-disease', "Crohn's Disease"],
  ['depression', 'Depression'],
  ['ehlers-danlos-syndrome', 'Ehlers-Danlos Syndrome'],
  ['endometriosis', 'Endometriosis'],
  ['epilepsy', 'Epilepsy (Adult & Child)'],
  ['fibromyalgia', 'Fibromyalgia'],
  ['insomnia', 'Insomnia'],
  ['low-back-pain-and-sciatica', 'Low Back Pain and Sciatica'],
  ['migraine', 'Migraine'],
  ['multiple-sclerosis', 'Multiple Sclerosis (MS)'],
  ['musculoskeletal-pain', 'Musculoskeletal Pain'],
  ['neuropathic-pain', 'Neuropathic Pain'],
  ['obsessive-compulsive-disorder', 'Obsessive Compulsive Disorder (OCD)'],
  ['other-gastrointestinal-condition', 'Other Gastrointestinal Condition'],
  ['other-neurological-disorder', 'Other Neurological Disorder'],
  ['palliative-care', 'Palliative Care'],
  ['parkinsons-disease', "Parkinson's Disease"],
  ['post-traumatic-stress-disorder', 'Post Traumatic Stress Disorder (PTSD)'],
  ['rare-or-challenging-skin-condition', 'Rare or Challenging Skin Condition'],
  ['social-phobia', 'Social Phobia'],
  ['tourettes-syndrome', "Tourette's Syndrome"],
  ['trigeminal-neuralgia', 'Trigeminal Neuralgia'],
  ['ulcerative-colitis', 'Ulcerative Colitis'],
] as const;

export const ELIGIBILITY_CONDITION_IDS = ELIGIBILITY_CONDITIONS.map(([id]) => id) as [
  typeof ELIGIBILITY_CONDITIONS[number][0],
  ...Array<typeof ELIGIBILITY_CONDITIONS[number][0]>,
];
