import type {
  CRMPatient,
  LineItem,
  PatientOrder,
  PharmacyTenant,
  Prescription,
} from '../context/AppContext';

export const TRAINING_REFERRAL_SOURCE = 'training_sandbox';

export const TRAINING_PRODUCT = {
  id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1',
  formulaId: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa2',
  name: 'Training flower 10g',
  packSize: 10,
  retail: 85,
  cost: 42,
  supplierState: 'ACTIVE',
} as const;

export const TRAINING_PRESCRIBER = {
  id: 'training-prescriber',
  name: 'Dr Training Clinic',
  gmcNumber: '7000001',
} as const;

export const ORGANISATIONS: PharmacyTenant[] = [
  {
    id: '3e9f74ff-4fed-497d-904d-4d3ee3e5e126',
    slug: 'primary-branch',
    referralToken: 'primary-branch-7x4p9k',
    name: 'Primary Branch',
    tradingName: 'Primary Branch',
    logoText: 'PB',
    gphcNumber: '1099224',
    superintendent: 'Shaylen Patel',
    companyNumber: '1099224',
    mainContactName: 'Shaylen Patel',
    mainContactPhone: '0113 000 0000',
    mainContactEmail: 'pharmacy@primarybranch.cc',
    curaleafPharmacyCode: '109c6bca-585a-4b69-b6bb-072e0731dd10',
    address: 'Leeds, West Yorkshire, United Kingdom',
    websiteDomains: ['primarybranch.cc'],
    status: 'onboarding',
    staffCount: 4,
    defaultPaymentRoute: 'manual',
    brand: { primary: '#0f766e', portalName: 'Primary Branch' },
    worldpay: { enabled: false, status: 'not-connected', environment: 'sandbox', merchantId: null, merchantName: null, lastSyncedAt: null },
  },
  {
    id: '6d0176bb-89a0-4e32-9bce-c934c9557c42',
    slug: 'eastwood-health-pharmacy',
    referralToken: 'eastwood-3m8q2v',
    name: 'Eastwood Health Pharmacy',
    tradingName: 'Eastwood Health Ltd',
    logoText: 'EH',
    gphcNumber: '9012726',
    superintendent: 'Shaylen Patel',
    companyNumber: '9012726',
    mainContactName: 'Shaylen Patel',
    mainContactPhone: '01522 000 000',
    mainContactEmail: 'contact@eastwoodhealthpharmacy.cc',
    curaleafPharmacyCode: '04568c82-b3d2-4082-9277-3313b48d10f4',
    address: 'Nottinghamshire, United Kingdom',
    websiteDomains: ['eastwoodhealthpharmacy.cc'],
    status: 'live',
    staffCount: 2,
    defaultPaymentRoute: 'manual',
    brand: { primary: '#1e40af', portalName: 'Eastwood Health Pharmacy' },
    worldpay: { enabled: false, status: 'not-connected', environment: 'sandbox', merchantId: null, merchantName: null, lastSyncedAt: null },
  },
];

export function isTrainingSandboxPatient(patient: Pick<CRMPatient, 'referralSource' | 'id'>): boolean {
  return patient.referralSource === TRAINING_REFERRAL_SOURCE || patient.id.startsWith('training-');
}

/** Pharmacy staff only have two workspaces: Live (real referred patients) or Training (examples). */
export function resolvePharmacyWorkspaceMode(organisation: Pick<PharmacyTenant, 'status' | 'workspaceClassification' | 'testAccount'> | null | undefined): 'live' | 'training' {
  if (!organisation) return 'training';
  if (organisation.workspaceClassification === 'allocation_holding') return 'live';
  if (organisation.workspaceClassification === 'training' || organisation.testAccount) return 'training';
  if (organisation.status === 'live' || organisation.status === 'paused') return 'live';
  return 'training';
}

export function trainingWorkspace(organisationId: string): {
  crm: CRMPatient[];
  orders: PatientOrder[];
  nextIds: { patient: number; rx: number; order: number; submission: number; invoice: number };
} {
  const daysAgo = (days: number) => new Date(Date.now() - days * 24 * 60 * 60 * 1000);
  const isoDay = (days: number) => daysAgo(days).toISOString().slice(0, 10);
  const pack: LineItem = {
    productId: TRAINING_PRODUCT.id,
    formulaId: TRAINING_PRODUCT.formulaId,
    name: TRAINING_PRODUCT.name,
    qty: 1,
    unitsNeededCount: TRAINING_PRODUCT.packSize,
    cost: TRAINING_PRODUCT.cost,
    retail: TRAINING_PRODUCT.retail,
  };
  const amount = TRAINING_PRODUCT.retail;

  const patients: CRMPatient[] = [
    {
      id: `training-${organisationId}-casey`,
      organisationId,
      name: 'Casey Reed',
      email: 'casey.reed@invalid.example',
      mobile: '00000 000 001',
      dob: '1991-04-12',
      postcode: 'XX0 0AA',
      conditions: ['Chronic pain'],
      primaryCondition: 'Chronic pain',
      referralSource: TRAINING_REFERRAL_SOURCE,
      status: 'Referred',
    },
    {
      id: `training-${organisationId}-jamie`,
      organisationId,
      name: 'Jamie Cole',
      email: 'jamie.cole@invalid.example',
      mobile: '00000 000 002',
      dob: '1986-09-03',
      postcode: 'XX0 0BB',
      conditions: ['Anxiety'],
      primaryCondition: 'Anxiety',
      referralSource: TRAINING_REFERRAL_SOURCE,
      status: 'HHH approved',
    },
    {
      id: `training-${organisationId}-morgan`,
      organisationId,
      name: 'Morgan Blake',
      email: 'morgan.blake@invalid.example',
      mobile: '00000 000 003',
      dob: '1978-01-22',
      postcode: 'XX0 0CC',
      conditions: ['Chronic pain'],
      primaryCondition: 'Chronic pain',
      referralSource: TRAINING_REFERRAL_SOURCE,
      status: 'HHH approved',
    },
    {
      id: `training-${organisationId}-riley`,
      organisationId,
      name: 'Riley Shah',
      email: 'riley.shah@invalid.example',
      mobile: '00000 000 004',
      dob: '1994-11-18',
      postcode: 'XX0 0DD',
      conditions: ['Insomnia'],
      primaryCondition: 'Insomnia',
      referralSource: TRAINING_REFERRAL_SOURCE,
      status: 'HHH approved',
    },
    {
      id: `training-${organisationId}-avery`,
      organisationId,
      name: 'Avery Quinn',
      email: 'avery.quinn@invalid.example',
      mobile: '00000 000 005',
      dob: '1983-06-09',
      postcode: 'XX0 0EE',
      conditions: ['Chronic pain'],
      primaryCondition: 'Chronic pain',
      referralSource: TRAINING_REFERRAL_SOURCE,
      status: 'HHH approved',
    },
    {
      id: `training-${organisationId}-taylor`,
      organisationId,
      name: 'Taylor West',
      email: 'taylor.west@invalid.example',
      mobile: '00000 000 006',
      dob: '1975-02-28',
      postcode: 'XX0 0FF',
      conditions: ['MS'],
      primaryCondition: 'MS',
      referralSource: TRAINING_REFERRAL_SOURCE,
      status: 'HHH approved',
    },
  ];

  const clinicRx = (id: number, status: Prescription['status'], extras: Partial<Prescription> = {}): Prescription => ({
    id,
    entryMode: 'clinic',
    clinicScanId: `training-scan-${id}`,
    curaleafPrescriptionId: `training-prescription-${id}`,
    curaleafPrescriptionState: extras.placed ? 'FULFILLED' : 'PENDING',
    curaleafPatientName: extras.curaleafPatientName,
    curaleafPatientDob: extras.curaleafPatientDob,
    prescriber: TRAINING_PRESCRIBER.name,
    prescriberId: TRAINING_PRESCRIBER.id,
    prescriberGmcNumber: TRAINING_PRESCRIBER.gmcNumber,
    serialNumber: `TRAINING-${isoDay(extras.placed ? 4 : 1).replaceAll('-', '')}-${id}`,
    issueDate: isoDay(extras.placed ? 4 : 1),
    expiryDate: isoDay(extras.placed ? -24 : -27),
    copyFileName: 'training-clinic-copy.pdf',
    items: [pack],
    placed: false,
    poRef: null,
    status,
    invoiceRef: null,
    trackingNumber: null,
    carrier: null,
    ...extras,
  });

  const orders: PatientOrder[] = [
    {
      id: 101,
      organisationId,
      patientId: patients[1].id,
      date: daysAgo(1),
      dispensingFee: 0,
      paymentRoute: 'manual',
      payment: {
        status: 'sent',
        route: 'pharmacy',
        amount,
        ref: 'TILL-TRAINING-101',
        sentAt: daysAgo(1),
        paidAt: null,
        manualTender: 'epos-card',
        manualReference: 'TILL-TRAINING-101',
        manualNotes: 'Training example — awaiting pharmacy-managed payment.',
        manualRecordedBy: 'Training workspace',
      },
      prescriptions: [clinicRx(1011, 'draft', {
        curaleafPatientName: patients[1].name,
        curaleafPatientDob: patients[1].dob,
      })],
    },
    {
      id: 102,
      organisationId,
      patientId: patients[2].id,
      date: daysAgo(2),
      dispensingFee: 0,
      paymentRoute: 'manual',
      payment: {
        status: 'paid',
        route: 'pharmacy',
        amount,
        ref: 'TILL-TRAINING-102',
        sentAt: daysAgo(2),
        paidAt: daysAgo(2),
        manualTender: 'epos-card',
        manualReference: 'TILL-TRAINING-102',
        manualNotes: 'Training example — paid, waiting for purchase order.',
        manualRecordedBy: 'Training workspace',
      },
      prescriptions: [clinicRx(1021, 'awaiting-approval', {
        curaleafPatientName: patients[2].name,
        curaleafPatientDob: patients[2].dob,
        curaleafPrescriptionState: 'PENDING',
      })],
    },
    {
      id: 103,
      organisationId,
      patientId: patients[3].id,
      date: daysAgo(5),
      dispensingFee: 0,
      paymentRoute: 'manual',
      payment: {
        status: 'paid',
        route: 'pharmacy',
        amount,
        ref: 'TILL-TRAINING-103',
        sentAt: daysAgo(5),
        paidAt: daysAgo(5),
        manualTender: 'cash',
        manualReference: 'TILL-TRAINING-103',
        manualNotes: 'Training example — purchase order in transit.',
        manualRecordedBy: 'Training workspace',
      },
      prescriptions: [clinicRx(1031, 'dispatched', {
        curaleafPatientName: patients[3].name,
        curaleafPatientDob: patients[3].dob,
        placed: true,
        placedAt: daysAgo(4),
        poRef: 'PO-TRAINING-103',
        purchaseOrderState: 'PROCESSING',
        dispatchStatus: 'complete',
        trackingNumber: 'TRN-103',
        carrier: 'Training courier',
        fulfilmentLines: [{
          productId: TRAINING_PRODUCT.id,
          ordered: 1,
          requested: 1,
          sent: 1,
          supplierReportedOrdered: 1,
          allocated: 1,
          shipped: 1,
          remaining: 0,
          received: 0,
          collected: 0,
          returned: 0,
          backordered: false,
          quantityMismatch: false,
        }],
      })],
    },
    {
      id: 104,
      organisationId,
      patientId: patients[4].id,
      date: daysAgo(8),
      dispensingFee: 0,
      paymentRoute: 'manual',
      payment: {
        status: 'paid',
        route: 'pharmacy',
        amount,
        ref: 'TILL-TRAINING-104',
        sentAt: daysAgo(8),
        paidAt: daysAgo(8),
        manualTender: 'bank-transfer',
        manualReference: 'TILL-TRAINING-104',
        manualNotes: 'Training example — ready for collection.',
        manualRecordedBy: 'Training workspace',
      },
      prescriptions: [clinicRx(1041, 'ready', {
        curaleafPatientName: patients[4].name,
        curaleafPatientDob: patients[4].dob,
        placed: true,
        placedAt: daysAgo(7),
        poRef: 'PO-TRAINING-104',
        purchaseOrderState: 'FULLY_ALLOCATED',
        dispatchStatus: 'complete',
        trackingNumber: 'TRN-104',
        carrier: 'Training courier',
        receivedItems: [{ productId: TRAINING_PRODUCT.id, quantityReceived: 1 }],
        goodsInAt: daysAgo(2),
        goodsInBy: 'Training workspace',
        readyAt: daysAgo(1),
        fulfilmentLines: [{
          productId: TRAINING_PRODUCT.id,
          ordered: 1,
          requested: 1,
          sent: 1,
          supplierReportedOrdered: 1,
          allocated: 1,
          shipped: 1,
          remaining: 0,
          received: 1,
          collected: 0,
          returned: 0,
          backordered: false,
          quantityMismatch: false,
        }],
      })],
    },
    {
      id: 105,
      organisationId,
      patientId: patients[5].id,
      date: daysAgo(14),
      dispensingFee: 0,
      paymentRoute: 'manual',
      payment: {
        status: 'paid',
        route: 'pharmacy',
        amount,
        ref: 'TILL-TRAINING-105',
        sentAt: daysAgo(14),
        paidAt: daysAgo(14),
        manualTender: 'epos-card',
        manualReference: 'TILL-TRAINING-105',
        manualNotes: 'Training example — collected.',
        manualRecordedBy: 'Training workspace',
      },
      prescriptions: [clinicRx(1051, 'collected', {
        curaleafPatientName: patients[5].name,
        curaleafPatientDob: patients[5].dob,
        placed: true,
        placedAt: daysAgo(13),
        poRef: 'PO-TRAINING-105',
        purchaseOrderState: 'FULLY_ALLOCATED',
        dispatchStatus: 'complete',
        trackingNumber: 'TRN-105',
        carrier: 'Training courier',
        receivedItems: [{ productId: TRAINING_PRODUCT.id, quantityReceived: 1 }],
        goodsInAt: daysAgo(10),
        goodsInBy: 'Training workspace',
        readyAt: daysAgo(9),
        fulfilmentLines: [{
          productId: TRAINING_PRODUCT.id,
          ordered: 1,
          requested: 1,
          sent: 1,
          supplierReportedOrdered: 1,
          allocated: 1,
          shipped: 1,
          remaining: 0,
          received: 1,
          collected: 1,
          returned: 0,
          backordered: false,
          quantityMismatch: false,
        }],
      })],
    },
  ];

  const nextRx = Math.max(...orders.flatMap(order => order.prescriptions.map(rx => rx.id)), 0) + 1;
  const nextOrder = Math.max(...orders.map(order => order.id), 0) + 1;

  return {
    crm: patients,
    orders,
    nextIds: { patient: 2000, rx: nextRx, order: nextOrder, submission: 5, invoice: 4072 },
  };
}
